<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\CentroUniversitario; // ✅ CORRECTO


class CentroUniversitarioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $centros = [
            // 🔹 Metropolitanos (6)
            [
                'nombre_rector' => 'Rector/a CUAAD',
                'tipo_centro_universitario' => 'Centro Universitario Metropolitano',
                'centro_universitario' => 'Centro Universitario de Arte, Arquitectura y Diseño',
                'siglas' => 'CUAAD',
                'direccion' => 'Guadalajara, Jalisco',
                'telefonos' => '33 3770 3300',
                'sitio_web' => 'https://www.cuaad.udg.mx',
                'colonia' => '',
                'codigo_postal' => '',
                'municipio' => 'Guadalajara',
                'estado' => 'Jalisco',
                'pais' => 'México',
                'vigente' => 1,
            ],
            [
                'nombre_rector' => 'Rector/a CUCEA',
                'tipo_centro_universitario' => 'Centro Universitario Metropolitano',
                'centro_universitario' => 'Centro Universitario de Ciencias Económico Administrativas',
                'siglas' => 'CUCEA',
                'direccion' => 'Zapopan, Jalisco',
                'telefonos' => '33 3770 3300',
                'sitio_web' => 'https://www.cucea.udg.mx',
                'colonia' => '',
                'codigo_postal' => '',
                'municipio' => 'Zapopan',
                'estado' => 'Jalisco',
                'pais' => 'México',
                'vigente' => 1,
            ],
            [
                'nombre_rector' => 'Rector/a CUCEI',
                'tipo_centro_universitario' => 'Centro Universitario Metropolitano',
                'centro_universitario' => 'Centro Universitario de Ciencias Exactas e Ingenierías',
                'siglas' => 'CUCEI',
                'direccion' => 'Guadalajara, Jalisco',
                'telefonos' => '33 3770 3300',
                'sitio_web' => 'https://www.cucei.udg.mx',
                'colonia' => '',
                'codigo_postal' => '',
                'municipio' => 'Guadalajara',
                'estado' => 'Jalisco',
                'pais' => 'México',
                'vigente' => 1,
            ],
            [
                'nombre_rector' => 'Rector/a CUCBA',
                'tipo_centro_universitario' => 'Centro Universitario Metropolitano',
                'centro_universitario' => 'Centro Universitario de Ciencias Biológicas y Agropecuarias',
                'siglas' => 'CUCBA',
                'direccion' => 'Zapopan, Jalisco',
                'telefonos' => '33 3770 3300',
                'sitio_web' => 'https://www.cucba.udg.mx',
                'colonia' => '',
                'codigo_postal' => '',
                'municipio' => 'Zapopan',
                'estado' => 'Jalisco',
                'pais' => 'México',
                'vigente' => 1,
            ],
            [
                'nombre_rector' => 'Rector/a CUCS',
                'tipo_centro_universitario' => 'Centro Universitario Metropolitano',
                'centro_universitario' => 'Centro Universitario de Ciencias de la Salud',
                'siglas' => 'CUCS',
                'direccion' => 'Guadalajara, Jalisco',
                'telefonos' => '33 3770 3300',
                'sitio_web' => 'https://www.cucs.udg.mx',
                'colonia' => '',
                'codigo_postal' => '',
                'municipio' => 'Guadalajara',
                'estado' => 'Jalisco',
                'pais' => 'México',
                'vigente' => 1,
            ],
            [
                'nombre_rector' => 'Rector/a CUCSH',
                'tipo_centro_universitario' => 'Centro Universitario Metropolitano',
                'centro_universitario' => 'Centro Universitario de Ciencias Sociales y Humanidades',
                'siglas' => 'CUCSH',
                'direccion' => 'Guadalajara, Jalisco',
                'telefonos' => '33 3770 3300',
                'sitio_web' => 'https://www.cucsh.udg.mx',
                'colonia' => '',
                'codigo_postal' => '',
                'municipio' => 'Guadalajara',
                'estado' => 'Jalisco',
                'pais' => 'México',
                'vigente' => 1,
            ],

            // 🔹 Regionales (9)
            [
                'nombre_rector' => 'Rector/a CUAltos',
                'tipo_centro_universitario' => 'Centro Universitario Regional',
                'centro_universitario' => 'Centro Universitario de los Altos',
                'siglas' => 'CUAltos',
                'direccion' => 'Tepatitlán, Jalisco',
                'telefonos' => '33 3770 3300',
                'sitio_web' => 'https://www.cualtos.udg.mx',
                'colonia' => '',
                'codigo_postal' => '',
                'municipio' => 'Tepatitlán',
                'estado' => 'Jalisco',
                'pais' => 'México',
                'vigente' => 1,
            ],
            [
                'nombre_rector' => 'Rector/a CUCiénega',
                'tipo_centro_universitario' => 'Centro Universitario Regional',
                'centro_universitario' => 'Centro Universitario de la Ciénega',
                'siglas' => 'CUCIÉNEGA',
                'direccion' => 'Ocotlán, Jalisco',
                'telefonos' => '33 3770 3300',
                'sitio_web' => 'https://www.cucienega.udg.mx',
                'colonia' => '',
                'codigo_postal' => '',
                'municipio' => 'Ocotlán',
                'estado' => 'Jalisco',
                'pais' => 'México',
                'vigente' => 1,
            ],
            [
                'nombre_rector' => 'Rector/a CUCosta',
                'tipo_centro_universitario' => 'Centro Universitario Regional',
                'centro_universitario' => 'Centro Universitario de la Costa',
                'siglas' => 'CUCosta',
                'direccion' => 'Puerto Vallarta, Jalisco',
                'telefonos' => '33 3770 3300',
                'sitio_web' => 'https://www.cuc.udg.mx',
                'colonia' => '',
                'codigo_postal' => '',
                'municipio' => 'Puerto Vallarta',
                'estado' => 'Jalisco',
                'pais' => 'México',
                'vigente' => 1,
            ],
            [
                'nombre_rector' => 'Rector/a CUCosta Sur',
                'tipo_centro_universitario' => 'Centro Universitario Regional',
                'centro_universitario' => 'Centro Universitario de la Costa Sur',
                'siglas' => 'CUCSUR',
                'direccion' => 'Autlán de Navarro, Jalisco',
                'telefonos' => '33 3770 3300',
                'sitio_web' => 'https://www.cucsur.udg.mx',
                'colonia' => '',
                'codigo_postal' => '',
                'municipio' => 'Autlán',
                'estado' => 'Jalisco',
                'pais' => 'México',
                'vigente' => 1,
            ],
            [
                'nombre_rector' => 'Rector/a CULagos',
                'tipo_centro_universitario' => 'Centro Universitario Regional',
                'centro_universitario' => 'Centro Universitario de los Lagos',
                'siglas' => 'CULagos',
                'direccion' => 'Lagos de Moreno, Jalisco',
                'telefonos' => '33 3770 3300',
                'sitio_web' => 'https://www.culagos.udg.mx',
                'colonia' => '',
                'codigo_postal' => '',
                'municipio' => 'Lagos de Moreno',
                'estado' => 'Jalisco',
                'pais' => 'México',
                'vigente' => 1,
            ],
            [
                'nombre_rector' => 'Rector/a CUNorte',
                'tipo_centro_universitario' => 'Centro Universitario Regional',
                'centro_universitario' => 'Centro Universitario del Norte',
                'siglas' => 'CUNorte',
                'direccion' => 'Colotlán, Jalisco',
                'telefonos' => '33 3770 3300',
                'sitio_web' => 'https://www.cunorte.udg.mx',
                'colonia' => '',
                'codigo_postal' => '',
                'municipio' => 'Colotlán',
                'estado' => 'Jalisco',
                'pais' => 'México',
                'vigente' => 1,
            ],
            [
                'nombre_rector' => 'Rector/a CUSur',
                'tipo_centro_universitario' => 'Centro Universitario Regional',
                'centro_universitario' => 'Centro Universitario del Sur',
                'siglas' => 'CUSur',
                'direccion' => 'Ciudad Guzmán, Jalisco',
                'telefonos' => '33 3770 3300',
                'sitio_web' => 'https://www.cusur.udg.mx',
                'colonia' => '',
                'codigo_postal' => '',
                'municipio' => 'Zapotlán el Grande',
                'estado' => 'Jalisco',
                'pais' => 'México',
                'vigente' => 1,
            ],
            [
                'nombre_rector' => 'Rector/a CUTonalá',
                'tipo_centro_universitario' => 'Centro Universitario Regional',
                'centro_universitario' => 'Centro Universitario de Tonalá',
                'siglas' => 'CUTonalá',
                'direccion' => 'Tonalá, Jalisco',
                'telefonos' => '33 3770 3300',
                'sitio_web' => 'https://www.cutonalá.udg.mx',
                'colonia' => '',
                'codigo_postal' => '',
                'municipio' => 'Tonalá',
                'estado' => 'Jalisco',
                'pais' => 'México',
                'vigente' => 1,
            ],
            [
                'nombre_rector' => 'Rector/a CUValles',
                'tipo_centro_universitario' => 'Centro Universitario Regional',
                'centro_universitario' => 'Centro Universitario de los Valles',
                'siglas' => 'CUValles',
                'direccion' => 'Ameca, Jalisco',
                'telefonos' => '33 3770 3300',
                'sitio_web' => 'https://www.cuvalles.udg.mx',
                'colonia' => '',
                'codigo_postal' => '',
                'municipio' => 'Ameca',
                'estado' => 'Jalisco',
                'pais' => 'México',
                'vigente' => 1,
            ],

            // 🔹 Temáticos (4)
            [
                'nombre_rector' => 'Rector/a UDGVirtual',
                'tipo_centro_universitario' => 'Centro Universitario Temático',
                'centro_universitario' => 'Centro Universitario de UDGVirtual',
                'siglas' => 'UDGVirtual',
                'direccion' => 'Guadalajara, Jalisco',
                'telefonos' => '33 3770 3300',
                'sitio_web' => 'https://www.udgvirtual.udg.mx',
                'colonia' => '',
                'codigo_postal' => '',
                'municipio' => 'Guadalajara',
                'estado' => 'Jalisco',
                'pais' => 'México',
                'vigente' => 1,
            ],
            [
                'nombre_rector' => 'Rector/a CUCS Digital',
                'tipo_centro_universitario' => 'Centro Universitario Temático',
                'centro_universitario' => 'Centro Universitario de Ciencias de la Salud Digital',
                'siglas' => 'CUCS Digital',
                'direccion' => 'Guadalajara, Jalisco',
                'telefonos' => '33 3770 3300',
                'sitio_web' => 'https://www.udgvirtual.udg.mx',
                'colonia' => '',
                'codigo_postal' => '',
                'municipio' => 'Guadalajara',
                'estado' => 'Jalisco',
                'pais' => 'México',
                'vigente' => 1,
            ],
            [
                'nombre_rector' => 'Rector/a CUCSH Virtual',
                'tipo_centro_universitario' => 'Centro Universitario Temático',
                'centro_universitario' => 'Centro Universitario de Ciencias Sociales y Humanidades Virtual',
                'siglas' => 'CUCSH Virtual',
                'direccion' => 'Guadalajara, Jalisco',
                'telefonos' => '33 3770 3300',
                'sitio_web' => 'https://www.udgvirtual.udg.mx',
                'colonia' => '',
                'codigo_postal' => '',
                'municipio' => 'Guadalajara',
                'estado' => 'Jalisco',
                'pais' => 'México',
                'vigente' => 1,
            ],
            [
                'nombre_rector' => 'Rector/a CUAAD Virtual',
                'tipo_centro_universitario' => 'Centro Universitario Temático',
                'centro_universitario' => 'Centro Universitario de Arte, Arquitectura y Diseño Virtual',
                'siglas' => 'CUAAD Virtual',
                'direccion' => 'Guadalajara, Jalisco',
                'telefonos' => '33 3770 3300',
                'sitio_web' => 'https://www.udgvirtual.udg.mx',
                'colonia' => '',
                'codigo_postal' => '',
                'municipio' => 'Guadalajara',
                'estado' => 'Jalisco',
                'pais' => 'México',
                'vigente' => 1,
            ],
        ];

        foreach ($centros as $data) {
            // Normaliza vacíos a NULL (coincide con columnas nullable)
            $data['colonia'] = ($data['colonia'] === '') ? null : $data['colonia'];
            $data['codigo_postal'] = ($data['codigo_postal'] === '') ? null : $data['codigo_postal'];

            // Upsert por 'siglas': si existe, actualiza; si no, crea
            CentroUniversitario::updateOrCreate(
                ['siglas' => $data['siglas']],   // clave de búsqueda
                $data                              // valores a crear/actualizar
            );
        }
    }
}
